create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password text not null,
  role text default 'syndic',
  name text,
  company_name text,
  phone text,
  address text,
  vat_number text,
  profile_completed boolean default false,
  email_verified boolean default false,
  verification_token text,
  reset_token text,
  reset_token_expires timestamptz,
  street text,
  number text,
  box text,
  zip text,
  city text,
  parent_id bigint references public.users(id) on delete set null,
  has_full_building_access boolean default false
);

create table if not exists public.buildings (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  street text,
  number text,
  box text,
  zip text,
  city text,
  syndic_name text,
  billing_info text,
  notes text,
  status text default 'pending_survey',
  survey_date timestamptz,
  gestionnaire_nom text,
  gestionnaire_email text,
  is_new_for_admin boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.signage (
  id bigint generated by default as identity primary key,
  building_id bigint not null references public.buildings(id) on delete cascade,
  category text not null,
  mount_type text not null,
  width double precision,
  height double precision,
  color_bg text,
  color_text text,
  font text,
  font_size double precision,
  location_detail text,
  notes text,
  image_data text,
  after_image_data text,
  material text
);

create table if not exists public.user_buildings (
  user_id bigint not null references public.users(id) on delete cascade,
  building_id bigint not null references public.buildings(id) on delete cascade,
  primary key (user_id, building_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  building_id bigint not null references public.buildings(id) on delete cascade,
  signage_id bigint references public.signage(id) on delete set null,
  requester_name text,
  requester_email text,
  requester_quality text,
  lot_number text,
  name_to_replace text,
  details text,
  status text default 'reçue',
  photo_before text,
  photo_after text,
  order_number text,
  owner_email text,
  owner_reference text,
  created_at timestamptz default now()
);

create table if not exists public.owners (
  id bigint generated by default as identity primary key,
  organization_user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  email text,
  created_at timestamptz default now()
);

create table if not exists public.building_owners (
  id bigint generated by default as identity primary key,
  building_id bigint not null references public.buildings(id) on delete cascade,
  owner_id bigint not null references public.owners(id) on delete cascade,
  reference text not null,
  is_primary boolean default false,
  created_at timestamptz default now(),
  unique (building_id, owner_id)
);

alter table public.orders add column if not exists owner_reference text;
alter table public.users add column if not exists has_full_building_access boolean default false;
alter table public.users add column if not exists first_name text;
alter table public.users add column if not exists last_name text;
alter table public.users add column if not exists bce_number text;
alter table public.users add column if not exists ipi_number text;
alter table public.users add column if not exists is_ipi_certified boolean default false;
alter table public.buildings add column if not exists created_by_user_id bigint references public.users(id) on delete set null;
alter table public.signage add column if not exists thickness text;
alter table public.signage add column if not exists shape text;
alter table public.signage add column if not exists corners text;
alter table public.signage add column if not exists marking_method text;

create table if not exists public.order_links (
  token text primary key,
  building_id bigint not null references public.buildings(id) on delete cascade,
  expires_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_signage_building_id on public.signage (building_id);
create index if not exists idx_orders_building_id on public.orders (building_id);
create index if not exists idx_orders_signage_id on public.orders (signage_id);
create index if not exists idx_notifications_user_id on public.notifications (user_id);
create index if not exists idx_owners_organization_user_id on public.owners (organization_user_id);
create index if not exists idx_building_owners_building_id on public.building_owners (building_id);
create index if not exists idx_building_owners_owner_id on public.building_owners (owner_id);
