-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.building_owners (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  building_id integer NOT NULL,
  owner_id integer NOT NULL,
  reference text NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT building_owners_pkey PRIMARY KEY (id),
  CONSTRAINT building_owners_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id),
  CONSTRAINT building_owners_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.owners(id)
);
CREATE TABLE public.building_syndic_assignments (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  building_id integer NOT NULL,
  syndic_user_id integer NOT NULL,
  assigned_by_user_id integer,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  unassigned_at timestamp with time zone,
  unassigned_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT building_syndic_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT building_syndic_assignments_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id),
  CONSTRAINT building_syndic_assignments_syndic_user_id_fkey FOREIGN KEY (syndic_user_id) REFERENCES public.users(id),
  CONSTRAINT building_syndic_assignments_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.building_transfer_requests (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  building_id integer NOT NULL,
  from_syndic_user_id integer,
  to_syndic_user_id integer NOT NULL,
  requested_by_user_id integer NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text, 'forced'::text, 'expired'::text])),
  reason text,
  evidence text,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  decided_at timestamp with time zone,
  decided_by_user_id integer,
  forced_by_admin boolean NOT NULL DEFAULT false,
  force_note text,
  CONSTRAINT building_transfer_requests_pkey PRIMARY KEY (id),
  CONSTRAINT building_transfer_requests_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id),
  CONSTRAINT building_transfer_requests_from_syndic_user_id_fkey FOREIGN KEY (from_syndic_user_id) REFERENCES public.users(id),
  CONSTRAINT building_transfer_requests_to_syndic_user_id_fkey FOREIGN KEY (to_syndic_user_id) REFERENCES public.users(id),
  CONSTRAINT building_transfer_requests_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id) REFERENCES public.users(id),
  CONSTRAINT building_transfer_requests_decided_by_user_id_fkey FOREIGN KEY (decided_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.buildings (
  id integer NOT NULL DEFAULT nextval('buildings_id_seq'::regclass),
  name text NOT NULL,
  address text NOT NULL,
  street text,
  number text,
  box text,
  zip text,
  city text,
  syndic_name text,
  billing_info text,
  notes text,
  gestionnaire_nom text,
  gestionnaire_email text,
  status text DEFAULT 'pending_survey'::text,
  survey_date timestamp with time zone,
  is_new_for_admin boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by_user_id integer,
  bce_number text,
  canonical_key text,
  archived_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT buildings_pkey PRIMARY KEY (id),
  CONSTRAINT buildings_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id integer NOT NULL DEFAULT nextval('notifications_id_seq'::regclass),
  user_id integer,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.order_links (
  token text NOT NULL,
  building_id integer NOT NULL,
  expires_at timestamp with time zone,
  created_by_user_id integer,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'revoked'::text, 'expired'::text])),
  max_uses integer NOT NULL DEFAULT 0,
  used_count integer NOT NULL DEFAULT 0,
  revoked_at timestamp with time zone,
  last_used_at timestamp with time zone,
  channel text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_links_pkey PRIMARY KEY (token),
  CONSTRAINT order_links_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id),
  CONSTRAINT order_links_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.orders (
  id integer NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
  building_id integer NOT NULL,
  signage_id integer,
  requester_name text,
  requester_email text,
  requester_quality text CHECK (requester_quality IS NULL OR (requester_quality = ANY (ARRAY['tenant'::text, 'owner'::text, 'syndic'::text, 'admin'::text]))),
  lot_number text,
  name_to_replace text,
  owner_email text,
  details text,
  order_number text,
  status text DEFAULT 'reçue'::text,
  photo_before text,
  photo_after text,
  created_at timestamp with time zone DEFAULT now(),
  owner_reference text,
  order_link_token text,
  request_source text DEFAULT 'web'::text,
  request_ip_hash text,
  request_fingerprint text,
  dedup_hash text,
  placeur_id integer,
  owner_approved_at timestamp with time zone,
  owner_rejected_at timestamp with time zone,
  photo_before_geo jsonb,
  photo_after_geo jsonb,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_placeur_id_fkey FOREIGN KEY (placeur_id) REFERENCES public.users(id),
  CONSTRAINT orders_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id),
  CONSTRAINT orders_signage_id_fkey FOREIGN KEY (signage_id) REFERENCES public.signage(id),
  CONSTRAINT orders_order_link_token_fkey FOREIGN KEY (order_link_token) REFERENCES public.order_links(token)
);
CREATE TABLE public.owners (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  organization_user_id integer NOT NULL,
  name text NOT NULL,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT owners_pkey PRIMARY KEY (id),
  CONSTRAINT owners_organization_user_id_fkey FOREIGN KEY (organization_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.sessions (
  token text NOT NULL,
  user_id integer NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sessions_pkey PRIMARY KEY (token),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.signage (
  id integer NOT NULL DEFAULT nextval('signage_id_seq'::regclass),
  building_id integer NOT NULL,
  category text NOT NULL,
  mount_type text NOT NULL,
  width real,
  height real,
  color_bg text,
  color_text text,
  font text,
  font_size real,
  location_detail text,
  notes text,
  material text,
  image_data text,
  after_image_data text,
  thickness text,
  shape text,
  corners text,
  marking_method text,
  CONSTRAINT signage_pkey PRIMARY KEY (id),
  CONSTRAINT signage_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id)
);
CREATE TABLE public.user_buildings (
  user_id integer NOT NULL,
  building_id integer NOT NULL,
  CONSTRAINT user_buildings_pkey PRIMARY KEY (user_id, building_id),
  CONSTRAINT user_buildings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_buildings_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id)
);
CREATE TABLE public.users (
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  email text NOT NULL UNIQUE,
  password text NOT NULL,
  role text DEFAULT 'syndic'::text,
  name text,
  company_name text,
  phone text,
  address text,
  street text,
  number text,
  box text,
  zip text,
  city text,
  vat_number text,
  profile_completed boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  verification_token text,
  reset_token text,
  reset_token_expires timestamp with time zone,
  parent_id integer,
  first_name text,
  last_name text,
  bce_number text,
  ipi_number text,
  is_ipi_certified boolean DEFAULT false,
  deleted_at timestamp with time zone,
  has_full_building_access boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.users(id)
);