-- Hall QR workflow (special order for Plachet)
-- One stable QR link per ACP, with replacement orders tracked separately.

begin;

create table if not exists public.hall_qr_orders (
  id integer generated by default as identity primary key,
  building_id integer not null references public.buildings(id) on delete cascade,
  order_link_token text references public.order_links(token) on delete set null,
  requested_by_user_id integer not null references public.users(id) on delete cascade,
  requested_by_role text not null default 'syndic',
  reason text not null default 'initial_install',
  status text not null default 'requested',
  is_replacement boolean not null default false,
  notes text,
  requested_at timestamptz not null default now(),
  processed_at timestamptz,
  processed_by_user_id integer references public.users(id) on delete set null,
  installed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'hall_qr_orders_status_chk'
  ) then
    alter table public.hall_qr_orders
      add constraint hall_qr_orders_status_chk
      check (status in ('requested', 'in_production', 'ready_to_install', 'installed', 'cancelled'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'hall_qr_orders_role_chk'
  ) then
    alter table public.hall_qr_orders
      add constraint hall_qr_orders_role_chk
      check (requested_by_role in ('syndic', 'admin'));
  end if;
end $$;

create index if not exists idx_hall_qr_orders_building_created_at
  on public.hall_qr_orders (building_id, created_at desc);

create index if not exists idx_hall_qr_orders_status_requested_at
  on public.hall_qr_orders (status, requested_at desc);

create index if not exists idx_hall_qr_orders_requested_by
  on public.hall_qr_orders (requested_by_user_id, requested_at desc);

create unique index if not exists uq_one_open_hall_qr_order_per_building
  on public.hall_qr_orders (building_id)
  where status in ('requested', 'in_production', 'ready_to_install');

commit;
