-- Foundation + workflow hardening migration
-- Target: current production schema shared in chat.
-- Safe to run multiple times (idempotent where possible).

begin;

create extension if not exists pgcrypto;
create extension if not exists citext;

-- ---------------------------------------------------------------------------
-- 1) ALIGN WITH CURRENT BACKEND USAGE
-- ---------------------------------------------------------------------------

-- users: columns used by backend/frontend but missing in some environments
alter table if exists public.users add column if not exists first_name text;
alter table if exists public.users add column if not exists last_name text;
alter table if exists public.users add column if not exists bce_number text;
alter table if exists public.users add column if not exists ipi_number text;
alter table if exists public.users add column if not exists is_ipi_certified boolean default false;
alter table if exists public.users add column if not exists has_full_building_access boolean default false;
alter table if exists public.users add column if not exists deleted_at timestamptz;

-- Convert integer flags to boolean when needed.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'users'
      and column_name = 'profile_completed'
      and data_type in ('smallint', 'integer', 'bigint')
  ) then
    execute 'alter table public.users alter column profile_completed drop default';
    execute 'alter table public.users alter column profile_completed type boolean using (coalesce(profile_completed, 0) <> 0)';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'users'
      and column_name = 'email_verified'
      and data_type in ('smallint', 'integer', 'bigint')
  ) then
    execute 'alter table public.users alter column email_verified drop default';
    execute 'alter table public.users alter column email_verified type boolean using (coalesce(email_verified, 0) <> 0)';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'users'
      and column_name = 'is_ipi_certified'
      and data_type in ('smallint', 'integer', 'bigint')
  ) then
    execute 'alter table public.users alter column is_ipi_certified drop default';
    execute 'alter table public.users alter column is_ipi_certified type boolean using (coalesce(is_ipi_certified, 0) <> 0)';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notifications'
      and column_name = 'is_read'
      and data_type in ('smallint', 'integer', 'bigint')
  ) then
    execute 'alter table public.notifications alter column is_read drop default';
    execute 'alter table public.notifications alter column is_read type boolean using (coalesce(is_read, 0) <> 0)';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'buildings'
      and column_name = 'is_new_for_admin'
      and data_type in ('smallint', 'integer', 'bigint')
  ) then
    execute 'alter table public.buildings alter column is_new_for_admin drop default';
    execute 'alter table public.buildings alter column is_new_for_admin type boolean using (coalesce(is_new_for_admin, 0) <> 0)';
  end if;
end $$;

alter table if exists public.users alter column profile_completed set default false;
alter table if exists public.users alter column email_verified set default false;
alter table if exists public.users alter column is_ipi_certified set default false;
alter table if exists public.notifications alter column is_read set default false;
alter table if exists public.buildings alter column is_new_for_admin set default true;

-- buildings: fields needed for ownership/recovery workflows
alter table if exists public.buildings add column if not exists bce_number text;
alter table if exists public.buildings add column if not exists canonical_key text;
alter table if exists public.buildings add column if not exists archived_at timestamptz;
alter table if exists public.buildings add column if not exists updated_at timestamptz default now();

-- owners and building_owners are used by backend routes; ensure they exist
create table if not exists public.owners (
  id integer generated by default as identity primary key,
  organization_user_id integer not null references public.users(id) on delete cascade,
  name text not null,
  email text,
  created_at timestamptz default now()
);

create table if not exists public.building_owners (
  id integer generated by default as identity primary key,
  building_id integer not null references public.buildings(id) on delete cascade,
  owner_id integer not null references public.owners(id) on delete cascade,
  reference text not null,
  is_primary boolean default false,
  created_at timestamptz default now()
);

create unique index if not exists uq_building_owners_building_owner
  on public.building_owners (building_id, owner_id);

create unique index if not exists uq_building_owners_reference_per_building
  on public.building_owners (building_id, reference);

create index if not exists idx_owners_org_user_id
  on public.owners (organization_user_id);

create unique index if not exists uq_owners_name_email_in_org
  on public.owners (organization_user_id, lower(name), coalesce(lower(email), ''));

-- orders: fields already referenced in code and useful for security
alter table if exists public.orders add column if not exists owner_reference text;
alter table if exists public.orders add column if not exists order_link_token text references public.order_links(token) on delete set null;
alter table if exists public.orders add column if not exists request_source text default 'web';
alter table if exists public.orders add column if not exists request_ip_hash text;
alter table if exists public.orders add column if not exists request_fingerprint text;
alter table if exists public.orders add column if not exists dedup_hash text;
alter table if exists public.orders add column if not exists owner_approved_at timestamptz;
alter table if exists public.orders add column if not exists owner_rejected_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_requester_quality_chk'
  ) then
    alter table public.orders
      add constraint orders_requester_quality_chk
      check (
        requester_quality is null
        or requester_quality in ('tenant', 'owner', 'syndic', 'admin')
      );
  end if;
end $$;

-- order_links: secure public links (QR / shared links)
alter table if exists public.order_links add column if not exists created_by_user_id integer references public.users(id) on delete set null;
alter table if exists public.order_links add column if not exists status text not null default 'active';
alter table if exists public.order_links add column if not exists max_uses integer not null default 0;
alter table if exists public.order_links add column if not exists used_count integer not null default 0;
alter table if exists public.order_links add column if not exists revoked_at timestamptz;
alter table if exists public.order_links add column if not exists last_used_at timestamptz;
alter table if exists public.order_links add column if not exists channel text;
alter table if exists public.order_links add column if not exists metadata jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'order_links_status_chk'
  ) then
    alter table public.order_links
      add constraint order_links_status_chk
      check (status in ('active', 'revoked', 'expired'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'order_links_max_uses_chk'
  ) then
    alter table public.order_links
      add constraint order_links_max_uses_chk
      check (
        max_uses >= 0
        and used_count >= 0
        and (
          (max_uses = 0)
          or (max_uses > 0 and used_count <= max_uses)
        )
      );
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 2) ACP MANAGEMENT / TRANSFER WORKFLOW (CAS 1/2/3)
-- ---------------------------------------------------------------------------

-- History table: who managed a building and when.
create table if not exists public.building_syndic_assignments (
  id integer generated by default as identity primary key,
  building_id integer not null references public.buildings(id) on delete cascade,
  syndic_user_id integer not null references public.users(id) on delete cascade,
  assigned_by_user_id integer references public.users(id) on delete set null,
  assigned_at timestamptz not null default now(),
  unassigned_at timestamptz,
  unassigned_reason text,
  created_at timestamptz not null default now()
);

-- 1 ACP = 1 syndic actif max.
create unique index if not exists uq_one_active_syndic_per_building
  on public.building_syndic_assignments (building_id)
  where unassigned_at is null;

create index if not exists idx_building_syndic_assignments_syndic
  on public.building_syndic_assignments (syndic_user_id, unassigned_at);

create index if not exists idx_building_syndic_assignments_building
  on public.building_syndic_assignments (building_id, unassigned_at);

-- Transfer requests for CAS 2 / CAS 3.
create table if not exists public.building_transfer_requests (
  id integer generated by default as identity primary key,
  building_id integer not null references public.buildings(id) on delete cascade,
  from_syndic_user_id integer references public.users(id) on delete set null,
  to_syndic_user_id integer not null references public.users(id) on delete cascade,
  requested_by_user_id integer not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  reason text,
  evidence text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by_user_id integer references public.users(id) on delete set null,
  forced_by_admin boolean not null default false,
  force_note text
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'building_transfer_requests_status_chk'
  ) then
    alter table public.building_transfer_requests
      add constraint building_transfer_requests_status_chk
      check (status in ('pending', 'approved', 'rejected', 'cancelled', 'forced', 'expired'));
  end if;
end $$;

create unique index if not exists uq_one_pending_transfer_per_building
  on public.building_transfer_requests (building_id)
  where status = 'pending';

create index if not exists idx_transfer_requests_target
  on public.building_transfer_requests (to_syndic_user_id, status, created_at desc);

create index if not exists idx_transfer_requests_source
  on public.building_transfer_requests (from_syndic_user_id, status, created_at desc);

-- ---------------------------------------------------------------------------
-- 3) ACP UNIQUENESS / SEARCH QUALITY
-- ---------------------------------------------------------------------------

-- Canonical key helps detect duplicates without freezing display name edits.
update public.buildings
set canonical_key =
  lower(regexp_replace(trim(coalesce(name, '')), '[[:space:]]+', ' ', 'g')) || '|' ||
  lower(trim(coalesce(zip, ''))) || '|' ||
  lower(trim(coalesce(number, ''))) || '|' ||
  lower(regexp_replace(trim(coalesce(street, '')), '[[:space:]]+', ' ', 'g'))
where canonical_key is null;

create index if not exists idx_buildings_canonical_key
  on public.buildings (canonical_key);

create unique index if not exists uq_buildings_bce_number
  on public.buildings (lower(bce_number))
  where bce_number is not null and bce_number <> '';

create index if not exists idx_buildings_name_zip_number
  on public.buildings (lower(name), zip, number);

-- ---------------------------------------------------------------------------
-- 4) PERFORMANCE / ANTISPAM INDEXES
-- ---------------------------------------------------------------------------

create index if not exists idx_orders_status_created_at
  on public.orders (status, created_at desc);

create index if not exists idx_orders_building_created_at
  on public.orders (building_id, created_at desc);

create index if not exists idx_orders_requester_email
  on public.orders (lower(requester_email));

create index if not exists idx_orders_owner_email
  on public.orders (lower(owner_email));

create unique index if not exists uq_orders_dedup_hash
  on public.orders (dedup_hash)
  where dedup_hash is not null;

create index if not exists idx_order_links_building_status_expires
  on public.order_links (building_id, status, expires_at);

create index if not exists idx_order_links_last_used
  on public.order_links (last_used_at desc nulls last);

commit;

-- ---------------------------------------------------------------------------
-- NOTE
-- ---------------------------------------------------------------------------
-- This migration prepares schema + security foundations.
-- Backend logic has been aligned in application code for:
-- 1) token validation on POST /api/orders,
-- 2) transfer workflow via CAS 1/2/3 tables,
-- 3) guarded order status transitions.
-- Remaining pre-prod hardening is mainly:
-- - public anti-bot layer (captcha),
-- - rate limiting on public order endpoints,
-- - full integration test coverage.
